### ISSUE TITLE
markdown图片显示

### ISSUE THREAD

**Issue by jshw** [5-say/laravel-4.1-simple-blog#10]
在后台编辑文章插入图片，预览正常，但是回到博客显示时图片未显示，直接显示原始内容![enter image description here](http://xcfimg2.qiniudn.com/image/620/a01083729f0211e3b4a6e0db5512b209.jpg)，将"enter image title here"去掉显示正常！

**Comment by 5-say** [comment]
BUG 已修复，请更新源码再试。
