### ISSUE TITLE
邮件发送

### ISSUE THREAD

**Issue by Yannyezixin** [5-say/laravel-4.1-simple-blog#11]
邮件发送不出时并没有任何的提示，注册成功后跳转到邮件已发送，qq邮箱也收不到

mail.php 的相关配置为：

'driver' => 'mail'

'host' => 'smtp.qq.com'

'port' => '25'

'username' => 'myqq@qq.com'

'password' => '*******'

**Comment by Yannyezixin** [comment]
问题已经解决，linux 下 默认不安装sendmail

**Comment by 5-say** [comment]
感谢您在问题解决后的回复，这对于其他遇到相同问题的朋友将是一个很好的参考。
最后，非常抱歉没有及时跟进您的这个问题，工作实在太忙。
