### ISSUE TITLE
phpDebugBar 如何展现？

### ISSUE THREAD

**Issue by supgeek-rod** [5-say/laravel-4.1-simple-blog#14]
1、laravel-4.1-simple-blog 不是自动开启的phpDebugBar吗？
2、依照 https://github.com/5-say/laravel-4.1-note/blob/master/03.Composer-资源包/%5B调试工具栏%5D-Laravel-4-Debugbar.md 在自己的项目中也不生效？
3、单独安装phpDebugBar，依照 http://phpdebugbar.com  首页方式，根目录新建index.php，require_once('vendor/autoload.php');   进行render();   也无效果

是否我这里缺少php拓展呢？

**Comment by 5-say** [comment]
如果你正常下载并安装了laravel-4.1-simple-blog这个项目，那么请打开文件`/app/config/packages/barryvdh/laravel-debugbar/config.php`注意第17行`'enabled' => false,` 这里我将它强行关闭了，如果需要可以设置为`true`，或者使用被注释掉的第16行。

**Comment by 5-say** [comment]
另外值得注意的是，本项目引入的依赖是 `barryvdh/laravel-debugbar` 而非 `phpDebugBar`。

**Comment by supgeek-rod** [comment]
非常感谢，问题已经解决
