### ISSUE TITLE
路径访问问题

### ISSUE THREAD

**Issue by Skqing** [5-say/laravel-4.1-simple-blog#17]
访问这个路径http://127.0.0.1/Laravel/public/5-say
出现：
    The requested URL /Laravel/public/5-say was not found on this server.

能不能提供默认表的SQL，以便更简单的使用mysql

**Comment by 5-say** [comment]
URL重写的问题，如果你不太明白我说的是什么，可以先尝试访问
http://127.0.0.1/Laravel/public/index.php/5-say
