### ISSUE TITLE
为什么路径中总要加上/public/呢

### ISSUE THREAD

**Issue by Skqing** [5-say/laravel-4.1-simple-blog#18]
为什么路径中总要加上/public/呢？
例如 http://localhost/demo/public
我想这样访问呢？
http://localhost/demo

**Comment by 5-say** [comment]
- 首先，相关的问题建议都集中在一个issue中，不需要重复提交issues。
- 现在来回答你的问题：public从字面上就很清晰的说明了这是一个公开目录，实际部署时需要将虚拟主机的根目录指向这里，如此就确保了其它位于public上层的目录的文件安全，因为访问者无法直接浏览到网站根目录的上级目录中的文件。

**Comment by Skqing** [comment]
哦, 好的, 知道了, 谢了!
