### ISSUE TITLE
Install ErrorException

### ISSUE THREAD

**Issue by TheDanielChen** [5-say/laravel-4.1-simple-blog#21]
ErrorException
Illegal offset type in isset or empty (View: D:\WWW\lablog\app\views\l\blog.blade.php) (View: D:\WWW\lablog\app\views\l\blog.blade.php)

**Comment by 5-say** [comment]
问题原因：script 函数改写后，传参方式简化，但对应模板中的调用未作修改。
目前问题已修复，请更新源码后重试。

**Comment by TheDanielChen** [comment]
3Q  very much
