### ISSUE TITLE
为什么会加载不了CSS了

### ISSUE THREAD

**Issue by fansi** [5-say/laravel-4.1-simple-blog#22]
老师，装上您的BLOG，访问server.php可以，访问public会出现Error 500  ，CSS加载不了，打开CSS会报错，是否还需要设置CSS JS的路由了，求解，试了好多次了！！

**Comment by 5-say** [comment]
确认几个问题：
1.是否已经开启了 apache 或 nginx 的 rewrite 模块。
2.是页面完全无法显示，还是仅仅样式无法载入。
3.请附上你页面中的CSS链接的地址。

**Comment by fansi** [comment]
我把 .htaccess <IfModule mod_rewrite.c>
RewriteEngine on RewriteCond % !^$
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php/$1 [QSA,PT,L]
</IfModule>

改成这样就行了 0.0

在 2014-07-12 12:00:10，"成武" notifications@github.com 写道：

确认几个问题：
1.是否已经开启了 apache 或 nginx 的 rewrite 模块。
2.是页面完全无法显示，还是仅仅样式无法载入。
3.请附上你页面中的CSS链接的地址。

**Comment by 5-say** [comment]
非常感谢你的跟进，这将为出现同样问题的朋友提供参考。

**Comment by fansi** [comment]
非常感谢老师的无私奉献，我的小项目传到nginx上无法使用，希望老师能提供个nginx的规则以供学习下，谢谢了！

在 2014-07-15 13:42:48，"成武" notifications@github.com 写道：

非常感谢你的跟进，这将为出现同样问题的朋友提供参考。

**Comment by 5-say** [comment]
通常测试的时候我会这么写

```
if (!-e $request_filename)
{
    rewrite ^/(.*)$ /index.php?/$1 last;
    break;
}
```

而更加严谨的做法请参考这里 [dilumdarshana/Laravel_config](https://github.com/dilumdarshana/Laravel_config/blob/master/config)。
