### ISSUE TITLE
请问 5-say 有没有想过搭建一个composer的中国镜像？

### ISSUE THREAD

**Issue by jason-chang** [5-say/laravel-4.1-simple-blog#23]
如题，composer的速度着实无语！

**Comment by 5-say** [comment]
目前还没有这个打算，群里有朋友建议过，但日常维护是一个大问题，大家都忙于各自的工作。
所以当下的解决方案只有自带扶梯了。
另外需要说明的是，composer 速度慢的主要原因并非自身，而是资源包分散于不同的平台，这些不同平台的连接问题造成了 composer 慢的假象。

**Comment by jason-chang** [comment]
我想过搭一个，无奈技术有限，英文捉急，到是如果有人搭了，捐助服务器什么的没得说。
再说 扶梯
  不知你们用什么呢
  我是 
 goagent 
- 
  export http_proxy=127.0.0.1：8087
  +
  git config http_proxy 127.0.0.1 
  但是总也没连上过。

**Comment by 5-say** [comment]
1.最有效的方法是 搭建一个 composer 然后做资源镜像，而资源镜像想要达到好的效果可不容易，oschina 和 csdn 都有在做知名项目的镜像，效果并不理想。（这里不仅要考虑自身服务器的速度，更重要的是同步的时效性）
2.关于扶梯，我是个懒人，直接买的VPN。

**Comment by jason-chang** [comment]
另外给发个 vpn卖家 和 群号吧。

**Comment by 5-say** [comment]
vpn在群里问吧，群里的朋友都很热心。
我目前在两个群
1.golaravel最早的一个群，目前已满员。官网放出了另一个群398195960，质量应该不错。
2.16406911，这个群我也在，学习氛围不错，交流的内容也比较有针对性。
ps：最近比较少开Q，有要紧事可以联系我邮箱。
