### ISSUE TITLE
代码结构的问题

### ISSUE THREAD

**Issue by zhangjianwai813** [5-say/laravel-4.1-simple-blog#24]
您好，我一直在自学laravel并且用它开发了一个项目。但是一直感觉我的代码结构和复用性不是特别好。我们这有一个技术经理他那边写东西时候有一个service层将很多业务逻辑都放在了service层，并且可重复复用。但是我就是不知道laravel有这样类似的东西吗？或者我改怎么使用呢？这个问题一直在困扰着我，我现在就是所有的业务结构都在controler里面。这要感觉代码复用不高。您能帮我解惑吗？谢谢您。

**Comment by 5-say** [comment]
### 何为 service 层

1、所谓 service 层，就是将通用逻辑进行封装，以提高复用性。从根本上来说它还是一些类文件的集合。
2、构造应用程序的 service 层，实际上就是我们封装了一些类，并且要确保在程序中可以进行内部调用。
3、脱离开框架的层面，单就 PHP 来说，只要是做好了 autoloader、确保我们建立的类文件可以被自动载入，便可以说我们有了一个独立的 service 层。（建立一个 `services` 文件夹，建立对应的 service 文件。例如：`UserService.php`。）
4、那么如何去调用呢？

``` php
    $userService = new UserService;
    $userService->myLogic();
```

> 是的，远没有你想象的那么复杂。

### 在 laravel 中我们该如何去做？

> 让我们沿用上面的例子

1、在 `app` 目录下创建 `services` 文件夹。
2、在 `services` 文件夹下创建 `UserService.php` 类文件。

```
    app
    |---services
        |---UserService.php
```

``` php
    class UserService
    {
        public function myLogic()
        {
            // do anything ...
            return 'something ...';
        }
    }
```

3、在 `/app/start/global.php` 文件中注册 `services` 文件夹。

``` php
    ClassLoader::addDirectories(array(

        app_path().'/commands',
        app_path().'/controllers',
        app_path().'/models',
        app_path().'/database/seeds',
        ...
        app_path().'/services',

    ));
```

4、现在我们就可以在程序的任何位置进行调用了。

``` php
    $userService = new UserService;
    $userService->myLogic();
```

5、显然上面的代码还不够优雅，我们还可以这么做。

``` php
    with(new UserService)->myLogic();
```

6、而我比较推崇下面这种调用方法，建议花时间了解一下 laravel 的 Ioc 容器。

``` php
    App::make('UserService')->myLogic();
```

### 我们还可以做的更多

> 下面的这种调用方式是不是更加优雅呢？
> 如果感兴趣的话，可以学习 laravel 的 Facades 并将它运用到你的代码中。

``` php
    UserService::myLogic();
```

**Comment by zhangjianwai813** [comment]
恩。这段时间我也思考了一下，确实是像您说的这个意思。我的做法跟您说的一样，就是在调用的时候比较挫一点，我在里面写了一个单例去实现这个sevice层，然后去调用。您今天所提供的这些方法，确实是之前我都没想到的，我应该在好好看一下相关文档。
我还想问您的是，要是您这个blog的demo要封装上service这层您会如何做呢。或者是不区分这层，您会怎么做呢？因为最近我们的技术经理说，MVC的实现方式太糙了，所以他才建议我加入这一层。

**Comment by 5-say** [comment]
1、“MVC的实现方式太糙了”这句话我不是很理解。
2、事实上这个 blog demo 以目前的代码量，基本是没有加入 service 层的必要的，并没有出现需要复用的逻辑部分。
