### ISSUE TITLE
可以提供数据库文件吗?

### ISSUE THREAD

**Issue by maxcp21** [5-say/laravel-4.1-simple-blog#25]
可以提供/app/database/migrations底下数据库文件吗?

**Comment by 5-say** [comment]
已经补充对应的迁移和填充文件，更新项目即可获取。
具体使用方法参见 [将项目数据库依赖变更为其它数据库的方法](https://github.com/5-say/laravel-4.1-simple-blog/blob/master/change-db.md)

**Comment by maxcp21** [comment]
感谢5-say，晚点忙完试试，谢谢分享

**Comment by maxcp21** [comment]
谢谢成武大哥，依照您的方式已完成安装，谢谢提供~

**Comment by maxcp21** [comment]
谢谢成武大哥，依照您的方式已完成安装，谢谢提供

**Comment by 5-say** [comment]
不必客气，一开始没有把迁移文件放上来也是我的失误，能够帮到你很开心。
