### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by safawo** [5-say/laravel-4.1-simple-blog#3]
代码中路径为 http://localhost/blog/public/auth/signin
但需要在URL的路由前面加上 /index.php  才可以访问，
即 http://localhost/blog/public/index.php/auth/signin
//未登录时，进入主界面，点击所有链接都存在这个问题

**Comment by 5-say** [comment]
已重新下载测试，路由没有问题，请确认是否正确开启了 Apache 的 rewrite_module。
