### ISSUE TITLE
首次运行就显示这个？

### ISSUE THREAD

**Issue by YeahloYip** [5-say/laravel-4.1-simple-blog#5]
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Cannot redeclare d() (previously declared in /home/wwwroot/yeixin.zsidea.cn/vendor/raveren/kint/Kint.class.php:543)
open: /home/wwwroot/yeixin.zsidea.cn/app/controllers/Assists/assist.php
{
    if (class_exists('Barryvdh\Debugbar\Facade')) {
        Barryvdh\Debugbar\Facade::enable();
        array_map(function ($x) { Barryvdh\Debugbar\Facade::info($x); }, func_get_args());
    } else {
        array_map(function ($x) { var_dump($x); }, func_get_args());
    }
}
// 如果必须要在非视图响应中使用
function d_()

**Comment by 5-say** [comment]
- 由于本项目引入的 laravel-debugbar 依赖于 maximebf/debugbar ，而后者在本次更新后引入了 raveren/kint，最终造成了函数定义的冲突，已将多余的函数移除。
- 已经安装的朋友可以参照 [这里](https://github.com/5-say/laravel-4.1-simple-blog/commit/6077394c5581c3e1a0639671312554ac4292b381) 移除多余的函数即可正常使用。
- 另外 kint 相当给力，大家尝试一下 dd() 有惊喜。
  @yeahlo84
