### ISSUE TITLE
只有首页可以访问

### ISSUE THREAD

**Issue by ipsound** [5-say/laravel-4.1-simple-blog#6]
登录、注册、文章内容等，均无法访问。

我是初学者。想看看实际的项目是如何使用的。
xampp环境。
未修改任何文件。
在源码根目录执行的composer install。

**Comment by 5-say** [comment]
以登陆为例，请附上本地访问的 URL 以及页面出现的提示信息。

**Comment by ipsound** [comment]
http://localhost/blog/auth/signin

出错提示:
Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.
Error 404
localhost
Apache/2.4.7 (Win32) OpenSSL/1.0.1e PHP/5.5.9

**Comment by 5-say** [comment]
请确认是否正确开启了 Apache 的 rewrite_module。

**Comment by ipsound** [comment]
确认开启。配置如下。另外，分页查看文章列表没问题。http://localhost/blog/?page=7正确显示。

```
LoadModule rewrite_module modules/mod_rewrite.so
<IfModule alias_module>
    Alias /blog "E:/apps/blog/htdocs/public"
    <Directory "E:/apps/blog/htdocs/public"> 
        Options Indexes FollowSymLinks
        AllowOverride All
        <IfVersion < 2.3 >
          Order allow,deny
          Allow from all
        </IfVersion>
        <IfVersion >= 2.3>
          Require all granted
        </IfVersion>
    </Directory> 
</IfModule>
```

**Comment by 5-say** [comment]
请尝试访问
http://localhost/blog/index.php/auth/signin

**Comment by ipsound** [comment]
可以访问了。
看来是rewrite的问题了？
原来是不显示index.php的。

**Comment by 5-say** [comment]
是的。
若确实开启了 rewrite，而框架附带的 .htaccess 文件在你的Apache环境中不起作用，那么请尝试下面这个版本： [golaravel.com/docs/4.1/installation/#pretty-urls](http://www.golaravel.com/docs/4.1/installation/#pretty-urls)

**Comment by ipsound** [comment]
我会尝试一下.htaccess的配置。谢谢啦。
