### ISSUE TITLE
laravel-4.1-simple-blog为什么本地调试登陆不了

### ISSUE THREAD

**Issue by flxxinge** [5-say/laravel-4.1-simple-blog#7]
登陆的是数据库user里的数据，但总提示用户名或密码错误

**Comment by 5-say** [comment]
请详细说明您登录所使用的 账号 和 密码

**Comment by flxxinge** [comment]
我用了你在readme里提供的admin@demo.com，111111，登录不上，自己注册了一个758416715@qq.com，111111，数据库里已经有这个user了，但还是登不上，是不是在本地调试mail没验证有关呢，顺便问下，本地localhost能能配置mail吗，非常谢谢你的回复，学习了。

------------------ 原始邮件 ------------------
发件人: "成武";notifications@github.com;
发送时间: 2014年3月21日(星期五) 晚上9:48
收件人: "5-say/laravel-4.1-simple-blog"laravel-4.1-simple-blog@noreply.github.com; 
抄送: "天巴都"758416719@qq.com; 
主题: Re: [laravel-4.1-simple-blog] laravel-4.1-simple-blog为什么本地调试登陆不了 (#7)

请详细说明您登录所使用的 账号 和 密码

**Comment by 5-say** [comment]
1. 已经重新下载压缩包，并安装测试（php 版本 5.3.10 及 5.4.26），均可正常登录。请重新下载安装测试。
2. 登录部分的逻辑并未对非激活用户进行限制。
3. 本地是可以搭建邮件服务器的，而测试时为了方便我一般使用 gmail 的 smtp。

**Comment by flxxinge** [comment]
新压缩包目录下没有vendor文件夹吗？报错！

**Comment by flxxinge** [comment]
把源码下的vendor文件夹复制进来后还是报错，php版本5.3.10

**Comment by 5-say** [comment]
项目说明中已经明确给出了安装方法，**需要通过 composer 进行安装**，并不是自带 vendor 目录，请详细阅读安装说明。

**Comment by flxxinge** [comment]
额，我按照您的步骤重新部署了，但是还是那个问题啊，在signin的时候用的管理员账号还是提示用户名或密码错误，我用的是mysql，已经原来的sqlite文件转成sql了，也成功导入了数据库，在database文件里也改过配置了，跟原来的问题一样，php版本5.3.10

------------------ 原始邮件 ------------------
发件人: "成武";notifications@github.com;
发送时间: 2014年3月23日(星期天) 下午3:24
收件人: "5-say/laravel-4.1-simple-blog"laravel-4.1-simple-blog@noreply.github.com; 
抄送: "天巴都"758416719@qq.com; 
主题: Re: [laravel-4.1-simple-blog] laravel-4.1-simple-blog为什么本地调试登陆不了 (#7)

项目说明中已经明确给出了安装方法，需要通过 composer 进行安装，并不是自带 vendor 目录，请详细阅读安装说明。

**Comment by flxxinge** [comment]
还有我sqlite转sql的时候是用那个sqlitemanager转的，转出来后不能直接导入，然后再手动改了点东西，比如  ' 改为 `   就成功导入了，会不会是用户名或密码字段多了什么空格之类的，所以错误啊，麻烦了，谢谢您！

------------------ 原始邮件 ------------------
发件人: "成武";notifications@github.com;
发送时间: 2014年3月23日(星期天) 下午3:24
收件人: "5-say/laravel-4.1-simple-blog"laravel-4.1-simple-blog@noreply.github.com; 
抄送: "天巴都"758416719@qq.com; 
主题: Re: [laravel-4.1-simple-blog] laravel-4.1-simple-blog为什么本地调试登陆不了 (#7)

项目说明中已经明确给出了安装方法，需要通过 composer 进行安装，并不是自带 vendor 目录，请详细阅读安装说明。

**Comment by 5-say** [comment]
鉴于你的情况特殊，特地花时间编写了一份说明文档，希望可以帮助你顺利的完成数据库的迁移。  
详细请查看：
- [变更项目数据库的方法](https://github.com/5-say/laravel-4.1-simple-blog/blob/master/change-db.md)

**Comment by flxxinge** [comment]
太牛了，谢谢大神帮助菜鸟，膜拜！

**Comment by flxxinge** [comment]
要学的很多，定当努力，不打扰了哈。

------------------ 原始邮件 ------------------
发件人: "成武";notifications@github.com;
发送时间: 2014年3月23日(星期天) 晚上7:39
收件人: "5-say/laravel-4.1-simple-blog"laravel-4.1-simple-blog@noreply.github.com; 
抄送: "天巴都"758416719@qq.com; 
主题: Re: [laravel-4.1-simple-blog] laravel-4.1-simple-blog为什么本地调试登陆不了 (#7)

不必客气。
