### ISSUE TITLE
本地更换为mysql数据库时报错

### ISSUE THREAD

**Issue by meyiaomiao** [5-say/laravel-4.1-simple-blog#8]
安装时会遇到这个问题 mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead 请问要怎么解决？

**Comment by 5-say** [comment]
已针对此问题作出调整，请更新程序再试。

**Comment by meyiaomiao** [comment]
刚测试过，问题解决了   楼主的博客很给力，点个赞，以后多来踩

**Comment by 5-say** [comment]
感谢您的关注，接下来的一段时间工作会非常的忙，不能及时跟进了。  
希望有更多的朋友参与到 laravel 的圈子，贡献更多有价值的中文资料，优秀的东西值得大家去付出，去推广。
