### ISSUE TITLE
关联操作问题

### ISSUE THREAD

**Issue by xiaobeicn** [5-say/laravel-4.1-simple-blog#9]
如果删除对文章的评论后，在到我的评论里会报错

**Comment by 5-say** [comment]
- 使用 admin@demo.com（管理员） 和 a1@a.com（普通用户） 两个账号同时进行测试，在 “用户中心” - “我的评论” 中进行评论的删除操作，并重新进入此页面，并未出现您描述的错误。
- 请再次核实，或提供更加详细的信息。

**Comment by xiaobeicn** [comment]
删除登录用户评论后 =》
1.Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException
【http://localhost/laravel4/public/psr-0#comments】=》没有此文章路径

2.ErrorException
Trying to get property of non-object (View: E:\wamp\www\laravel4\app\views\account\myComments.blade.php)
【http://localhost/laravel4/public/account/my-comments】=》用户中心我的评论路径

**Comment by 5-say** [comment]
- 再次测试（直接在数据库中将所有评论删除）依然无报错，请重新下载安装。

**Comment by xiaobeicn** [comment]
我不是说删除评论，是删除带有评论的文章，然后进入用户中心=》我的评论，会报错~~

**Comment by 5-say** [comment]
终于说到点子上了，我也刚刚意识到了这个问题，会尽快做出修正。

**Comment by xiaobeicn** [comment]
是我表达的问题~

**Comment by 5-say** [comment]
顺便征求一下你的意见，文章删除后“我的评论”中对应的评论，是显示为“文章已删除”，还是直接就不显示了比较好。

**Comment by xiaobeicn** [comment]
如果是单用户（自己博客），就可以在提示的基础上直接删除，如果是多用户（团队博客）最好是列出评论，告诉其他用户该文章删除，不然都不知道自己评论怎么没得~~

**Comment by 5-say** [comment]
非常好的建议，谢谢。
